// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/food/presentation/view%20model/food_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/core/base/api_result.dart' as _i5;
import 'package:fitness_app/features/food/data/models/food_categories_response.dart'
    as _i6;
import 'package:fitness_app/features/food/data/models/meals_of_category_response.dart'
    as _i9;
import 'package:fitness_app/features/food/domain/repos/food_repo.dart' as _i2;
import 'package:fitness_app/features/food/domain/usecases/get_food_categories_usecase.dart'
    as _i3;
import 'package:fitness_app/features/food/domain/usecases/get_meals_of_category_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFoodRepo_0 extends _i1.SmartFake implements _i2.FoodRepo {
  _FakeFoodRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFoodCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFoodCategoriesUseCase extends _i1.Mock
    implements _i3.GetFoodCategoriesUseCase {
  MockGetFoodCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FoodRepo get foodRepo => (super.noSuchMethod(
        Invocation.getter(#foodRepo),
        returnValue: _FakeFoodRepo_0(
          this,
          Invocation.getter(#foodRepo),
        ),
      ) as _i2.FoodRepo);

  @override
  _i4.Future<_i5.ApiResult<_i6.FoodCategoriesResponse>> invoke() =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i6.FoodCategoriesResponse>>.value(
                _i7.dummyValue<_i5.ApiResult<_i6.FoodCategoriesResponse>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i6.FoodCategoriesResponse>>);
}

/// A class which mocks [GetMealsByCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealsByCategoryUseCase extends _i1.Mock
    implements _i8.GetMealsByCategoryUseCase {
  MockGetMealsByCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FoodRepo get foodRepo => (super.noSuchMethod(
        Invocation.getter(#foodRepo),
        returnValue: _FakeFoodRepo_0(
          this,
          Invocation.getter(#foodRepo),
        ),
      ) as _i2.FoodRepo);

  @override
  _i4.Future<_i5.ApiResult<_i9.MealsOfCategoryResponse>> invoke(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [category],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i9.MealsOfCategoryResponse>>.value(
                _i7.dummyValue<_i5.ApiResult<_i9.MealsOfCategoryResponse>>(
          this,
          Invocation.method(
            #invoke,
            [category],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i9.MealsOfCategoryResponse>>);
}
