// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/food/data/repos/food_repo_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/base/api_result.dart' as _i4;
import 'package:fitness_app/features/food/data/data%20sources/food_data_source.dart'
    as _i2;
import 'package:fitness_app/features/food/data/models/food_categories_response.dart'
    as _i5;
import 'package:fitness_app/features/food/data/models/meals_of_category_response.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FoodRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodRemoteDataSource extends _i1.Mock
    implements _i2.FoodRemoteDataSource {
  MockFoodRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.FoodCategoriesResponse>> getFoodCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFoodCategories,
          [],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.FoodCategoriesResponse>>.value(
                _i6.dummyValue<_i4.ApiResult<_i5.FoodCategoriesResponse>>(
          this,
          Invocation.method(
            #getFoodCategories,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.FoodCategoriesResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.MealsOfCategoryResponse>> getMealsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsByCategory,
          [category],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i7.MealsOfCategoryResponse>>.value(
                _i6.dummyValue<_i4.ApiResult<_i7.MealsOfCategoryResponse>>(
          this,
          Invocation.method(
            #getMealsByCategory,
            [category],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i7.MealsOfCategoryResponse>>);
}
