sonar.projectKey=Mariam2572_fitness_app
sonar.organization=mariam2572
sonar.host.url=https://sonarcloud.io
sonar.sources=lib
sonar.exclusions=**/*.g.dart
sonar.language=dart
sonar.dart.analysis.reportPaths=build/analysis/result.sarif
