// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/auth/change%20password/presentation/view%20model/change_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/core/base/api_result.dart' as _i5;
import 'package:fitness_app/features/auth/change%20password/data/model/change_password_request.dart'
    as _i7;
import 'package:fitness_app/features/auth/change%20password/data/model/change_password_response.dart'
    as _i6;
import 'package:fitness_app/features/auth/change%20password/domain/repo/change_pssword_repo.dart'
    as _i2;
import 'package:fitness_app/features/auth/change%20password/domain/usecase/change_passwrod_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChangePasswordRepo_0 extends _i1.SmartFake
    implements _i2.ChangePasswordRepo {
  _FakeChangePasswordRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i3.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChangePasswordRepo get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeChangePasswordRepo_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.ChangePasswordRepo);

  @override
  _i4.Future<_i5.ApiResult<_i6.ChangePasswordResponse>> invoke(
          _i7.ChangePasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [request],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i6.ChangePasswordResponse>>.value(
                _i8.dummyValue<_i5.ApiResult<_i6.ChangePasswordResponse>>(
          this,
          Invocation.method(
            #invoke,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i6.ChangePasswordResponse>>);
}
