// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/features/workOuts/domain/use_cases/get_all_muscles_groups_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/base/api_result.dart' as _i4;
import 'package:fitness_app/features/workOuts/data/models/response/get_all_muscles_by_muscle_group_id_reponse.dart'
    as _i7;
import 'package:fitness_app/features/workOuts/data/models/response/get_all_muscles_groups_reponse.dart'
    as _i5;
import 'package:fitness_app/features/workOuts/domain/repos/work_outs_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkOutsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkOutsRepo extends _i1.Mock implements _i2.WorkOutsRepo {
  MockWorkOutsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.GetAllMusclesGroupsReponse>>
      getAllMusclesGroups() => (super.noSuchMethod(
            Invocation.method(
              #getAllMusclesGroups,
              [],
            ),
            returnValue: _i3
                .Future<_i4.ApiResult<_i5.GetAllMusclesGroupsReponse>>.value(
                _i6.dummyValue<_i4.ApiResult<_i5.GetAllMusclesGroupsReponse>>(
              this,
              Invocation.method(
                #getAllMusclesGroups,
                [],
              ),
            )),
          ) as _i3.Future<_i4.ApiResult<_i5.GetAllMusclesGroupsReponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.GetAllMusclesByMuscleGroupIdReponse>>
      getAllMusclesByMuscleGroupId(String? id) => (super.noSuchMethod(
            Invocation.method(
              #getAllMusclesByMuscleGroupId,
              [id],
            ),
            returnValue: _i3.Future<
                    _i4
                    .ApiResult<_i7.GetAllMusclesByMuscleGroupIdReponse>>.value(
                _i6.dummyValue<
                    _i4.ApiResult<_i7.GetAllMusclesByMuscleGroupIdReponse>>(
              this,
              Invocation.method(
                #getAllMusclesByMuscleGroupId,
                [id],
              ),
            )),
          ) as _i3
              .Future<_i4.ApiResult<_i7.GetAllMusclesByMuscleGroupIdReponse>>);
}
