// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWCChjEaaeGg_NufcVxT3asFzTJ_xdfM',
    appId: '1:736715152917:web:d5e419bce02960e6b9381c',
    messagingSenderId: '736715152917',
    projectId: 'fitness-app-de61e',
    authDomain: 'fitness-app-de61e.firebaseapp.com',
    storageBucket: 'fitness-app-de61e.firebasestorage.app',
    measurementId: 'G-73L79H2RKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jwkJp0TIEGQeskxM4wdHtqntuSwIjYQ',
    appId: '1:736715152917:android:600402aae56c901db9381c',
    messagingSenderId: '736715152917',
    projectId: 'fitness-app-de61e',
    storageBucket: 'fitness-app-de61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiLd_YblhrhqtDg1EOjqjT_qlbLu0ENC0',
    appId: '1:736715152917:ios:09ab5c300abe3cb5b9381c',
    messagingSenderId: '736715152917',
    projectId: 'fitness-app-de61e',
    storageBucket: 'fitness-app-de61e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiLd_YblhrhqtDg1EOjqjT_qlbLu0ENC0',
    appId: '1:736715152917:ios:09ab5c300abe3cb5b9381c',
    messagingSenderId: '736715152917',
    projectId: 'fitness-app-de61e',
    storageBucket: 'fitness-app-de61e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMWCChjEaaeGg_NufcVxT3asFzTJ_xdfM',
    appId: '1:736715152917:web:96178ac6f7cf6218b9381c',
    messagingSenderId: '736715152917',
    projectId: 'fitness-app-de61e',
    authDomain: 'fitness-app-de61e.firebaseapp.com',
    storageBucket: 'fitness-app-de61e.firebasestorage.app',
    measurementId: 'G-5QM9FN3D66',
  );
}
