// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/features/exercise/data/data_source/exercise_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i16;

import 'package:fitness_app/core/api_manager/api_services.dart' as _i12;
import 'package:fitness_app/features/auth/change%20password/data/model/change_password_request.dart'
    as _i18;
import 'package:fitness_app/features/auth/change%20password/data/model/change_password_response.dart'
    as _i11;
import 'package:fitness_app/features/auth/login/data/model/login_request/login_request.dart'
    as _i14;
import 'package:fitness_app/features/auth/login/data/model/login_response/login_response.dart'
    as _i2;
import 'package:fitness_app/features/auth/register/data/models/request/register_request.dart'
    as _i15;
import 'package:fitness_app/features/auth/register/data/models/response/register_response.dart'
    as _i3;
import 'package:fitness_app/features/exercise/data/models/exercise_by_prime_mover_and_difficulty_model/exercise_by_prime_mover_and_difficulty_response.dart'
    as _i4;
import 'package:fitness_app/features/exercise/data/models/levels_by_muscles_model.dart'
    as _i5;
import 'package:fitness_app/features/home/home/data/models/ExercisesResponse.dart'
    as _i8;
import 'package:fitness_app/features/home/home/data/models/RandomExerciseResponse.dart'
    as _i10;
import 'package:fitness_app/features/home/home/data/models/UserResponse.dart'
    as _i9;
import 'package:fitness_app/features/workOuts/data/models/response/get_all_muscles_by_muscle_group_id_reponse.dart'
    as _i7;
import 'package:fitness_app/features/workOuts/data/models/response/get_all_muscles_groups_reponse.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponse_1 extends _i1.SmartFake
    implements _i3.RegisterResponse {
  _FakeRegisterResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExerciseByPrimeMoverAndDifficultyResponse_2 extends _i1.SmartFake
    implements _i4.ExerciseByPrimeMoverAndDifficultyResponse {
  _FakeExerciseByPrimeMoverAndDifficultyResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeLevelsByMusclesModel_3 extends _i1.SmartFake
    implements _i5.LevelsByMusclesModel {
  _FakeLevelsByMusclesModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllMusclesGroupsReponse_4 extends _i1.SmartFake
    implements _i6.GetAllMusclesGroupsReponse {
  _FakeGetAllMusclesGroupsReponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllMusclesByMuscleGroupIdReponse_5 extends _i1.SmartFake
    implements _i7.GetAllMusclesByMuscleGroupIdReponse {
  _FakeGetAllMusclesByMuscleGroupIdReponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeExercisesResponse_6 extends _i1.SmartFake
    implements _i8.ExercisesResponse {
  _FakeExercisesResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_7 extends _i1.SmartFake implements _i9.UserResponse {
  _FakeUserResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomExerciseResponse_8 extends _i1.SmartFake
    implements _i10.RandomExerciseResponse {
  _FakeRandomExerciseResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponse_9 extends _i1.SmartFake
    implements _i11.ChangePasswordResponse {
  _FakeChangePasswordResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i12.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.LoginResponse> loginUser(_i14.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [loginRequest]),
            returnValue: _i13.Future<_i2.LoginResponse>.value(
              _FakeLoginResponse_0(
                this,
                Invocation.method(#loginUser, [loginRequest]),
              ),
            ),
          )
          as _i13.Future<_i2.LoginResponse>);

  @override
  _i13.Future<_i3.RegisterResponse> register(
    _i15.RegisterRequest? registerRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [registerRequest]),
            returnValue: _i13.Future<_i3.RegisterResponse>.value(
              _FakeRegisterResponse_1(
                this,
                Invocation.method(#register, [registerRequest]),
              ),
            ),
          )
          as _i13.Future<_i3.RegisterResponse>);

  @override
  _i13.Future<_i4.ExerciseByPrimeMoverAndDifficultyResponse>
  getExerciseByMoverAndDifficulty(
    String? primeMoverMuscleId,
    String? difficultyLevelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseByMoverAndDifficulty, [
              primeMoverMuscleId,
              difficultyLevelId,
            ]),
            returnValue: _i13.Future<
              _i4.ExerciseByPrimeMoverAndDifficultyResponse
            >.value(
              _FakeExerciseByPrimeMoverAndDifficultyResponse_2(
                this,
                Invocation.method(#getExerciseByMoverAndDifficulty, [
                  primeMoverMuscleId,
                  difficultyLevelId,
                ]),
              ),
            ),
          )
          as _i13.Future<_i4.ExerciseByPrimeMoverAndDifficultyResponse>);

  @override
  _i13.Future<_i5.LevelsByMusclesModel> getLevelsByMuscles(
    String? primeMoverMuscleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLevelsByMuscles, [primeMoverMuscleId]),
            returnValue: _i13.Future<_i5.LevelsByMusclesModel>.value(
              _FakeLevelsByMusclesModel_3(
                this,
                Invocation.method(#getLevelsByMuscles, [primeMoverMuscleId]),
              ),
            ),
          )
          as _i13.Future<_i5.LevelsByMusclesModel>);

  @override
  _i13.Future<_i6.GetAllMusclesGroupsReponse> getAllMusclesGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMusclesGroups, []),
            returnValue: _i13.Future<_i6.GetAllMusclesGroupsReponse>.value(
              _FakeGetAllMusclesGroupsReponse_4(
                this,
                Invocation.method(#getAllMusclesGroups, []),
              ),
            ),
          )
          as _i13.Future<_i6.GetAllMusclesGroupsReponse>);

  @override
  _i13.Future<_i7.GetAllMusclesByMuscleGroupIdReponse>
  getAllMusclesByMuscleGroupId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAllMusclesByMuscleGroupId, [id]),
            returnValue:
                _i13.Future<_i7.GetAllMusclesByMuscleGroupIdReponse>.value(
                  _FakeGetAllMusclesByMuscleGroupIdReponse_5(
                    this,
                    Invocation.method(#getAllMusclesByMuscleGroupId, [id]),
                  ),
                ),
          )
          as _i13.Future<_i7.GetAllMusclesByMuscleGroupIdReponse>);

  @override
  _i13.Future<_i8.ExercisesResponse> getAllExercises() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExercises, []),
            returnValue: _i13.Future<_i8.ExercisesResponse>.value(
              _FakeExercisesResponse_6(
                this,
                Invocation.method(#getAllExercises, []),
              ),
            ),
          )
          as _i13.Future<_i8.ExercisesResponse>);

  @override
  _i13.Future<_i9.UserResponse> getUserData(String? userToken) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [userToken]),
            returnValue: _i13.Future<_i9.UserResponse>.value(
              _FakeUserResponse_7(
                this,
                Invocation.method(#getUserData, [userToken]),
              ),
            ),
          )
          as _i13.Future<_i9.UserResponse>);

  @override
  _i13.Future<_i10.RandomExerciseResponse> getRandomExercises(
    String? targetMuscleGroupId,
    String? difficultyLevelId,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomExercises, [
              targetMuscleGroupId,
              difficultyLevelId,
              limit,
            ]),
            returnValue: _i13.Future<_i10.RandomExerciseResponse>.value(
              _FakeRandomExerciseResponse_8(
                this,
                Invocation.method(#getRandomExercises, [
                  targetMuscleGroupId,
                  difficultyLevelId,
                  limit,
                ]),
              ),
            ),
          )
          as _i13.Future<_i10.RandomExerciseResponse>);

  @override
  _i13.Future<String> uploadPhoto(_i16.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [image]),
            returnValue: _i13.Future<String>.value(
              _i17.dummyValue<String>(
                this,
                Invocation.method(#uploadPhoto, [image]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<_i9.UserResponse> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i13.Future<_i9.UserResponse>.value(
              _FakeUserResponse_7(this, Invocation.method(#getProfileData, [])),
            ),
          )
          as _i13.Future<_i9.UserResponse>);

  @override
  _i13.Future<_i11.ChangePasswordResponse> changePassword(
    _i18.ChangePasswordRequest? ChangePasswordRequest,
    String? userToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [
              ChangePasswordRequest,
              userToken,
            ]),
            returnValue: _i13.Future<_i11.ChangePasswordResponse>.value(
              _FakeChangePasswordResponse_9(
                this,
                Invocation.method(#changePassword, [
                  ChangePasswordRequest,
                  userToken,
                ]),
              ),
            ),
          )
          as _i13.Future<_i11.ChangePasswordResponse>);

  @override
  _i12.Future<String> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i12.Future<String>.value(
              _i15.dummyValue<String>(this, Invocation.method(#logout, [])),
            ),
          )
          as _i12.Future<String>);
}
