// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/features/exercise/domain/use_cases/get_exercise_by_mover_and_difficulty_level_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/base/api_result.dart' as _i4;
import 'package:fitness_app/features/exercise/data/models/exercise_by_prime_mover_and_difficulty_model/exercise_by_prime_mover_and_difficulty_response.dart'
    as _i7;
import 'package:fitness_app/features/exercise/data/models/levels_by_muscles_model.dart'
    as _i5;
import 'package:fitness_app/features/exercise/domain/repos/exercise_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExerciseRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepo extends _i1.Mock implements _i2.ExerciseRepo {
  MockExerciseRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LevelsByMusclesModel>> getLevelsByMuscles({
    required String? primeMoverMuscleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLevelsByMuscles, [], {
              #primeMoverMuscleId: primeMoverMuscleId,
            }),
            returnValue:
                _i3.Future<_i4.ApiResult<_i5.LevelsByMusclesModel>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i5.LevelsByMusclesModel>>(
                    this,
                    Invocation.method(#getLevelsByMuscles, [], {
                      #primeMoverMuscleId: primeMoverMuscleId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.LevelsByMusclesModel>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.ExerciseByPrimeMoverAndDifficultyResponse>>
  getExerciseByMoverAndDifficultyLevel({
    required String? primeMoverMuscleId,
    required String? difficultyLevelId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseByMoverAndDifficultyLevel, [], {
              #primeMoverMuscleId: primeMoverMuscleId,
              #difficultyLevelId: difficultyLevelId,
            }),
            returnValue: _i3.Future<
              _i4.ApiResult<_i7.ExerciseByPrimeMoverAndDifficultyResponse>
            >.value(
              _i6.dummyValue<
                _i4.ApiResult<_i7.ExerciseByPrimeMoverAndDifficultyResponse>
              >(
                this,
                Invocation.method(#getExerciseByMoverAndDifficultyLevel, [], {
                  #primeMoverMuscleId: primeMoverMuscleId,
                  #difficultyLevelId: difficultyLevelId,
                }),
              ),
            ),
          )
          as _i3.Future<
            _i4.ApiResult<_i7.ExerciseByPrimeMoverAndDifficultyResponse>
          >);
}
