// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/home/domain/home_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/core/base/api_result.dart' as _i5;
import 'package:fitness_app/features/food/data/models/food_categories_response.dart'
    as _i8;
import 'package:fitness_app/features/home/home/data/models/exercises_response.dart'
    as _i9;
import 'package:fitness_app/features/home/home/data/models/random_exercise_response.dart'
    as _i7;
import 'package:fitness_app/features/home/home/data/models/user_response.dart'
    as _i15;
import 'package:fitness_app/features/home/home/domain/repositories/home_repo.dart'
    as _i3;
import 'package:fitness_app/features/profile/domain/repos/profile_repo.dart'
    as _i2;
import 'package:fitness_app/features/profile/domain/use_case/get_profile_data_use_case.dart'
    as _i14;
import 'package:fitness_app/features/workOuts/data/models/response/get_all_muscles_by_muscle_group_id_reponse.dart'
    as _i13;
import 'package:fitness_app/features/workOuts/data/models/response/get_all_muscles_groups_reponse.dart'
    as _i11;
import 'package:fitness_app/features/workOuts/domain/use_cases/get_all_muscles_by_muscle_group_id_use_case.dart'
    as _i12;
import 'package:fitness_app/features/workOuts/domain/use_cases/get_all_muscles_groups_use_case.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileRepository_0 extends _i1.SmartFake
    implements _i2.ProfileRepository {
  _FakeProfileRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepo extends _i1.Mock implements _i3.HomeRepo {
  MockHomeRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<String>> getCurrentUserName() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserName,
          [],
        ),
        returnValue: _i4.Future<_i5.ApiResult<String>>.value(
            _i6.dummyValue<_i5.ApiResult<String>>(
          this,
          Invocation.method(
            #getCurrentUserName,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<String>>);

  @override
  _i4.Future<_i5.ApiResult<_i7.RandomExerciseResponse>> getRandomExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomExercises,
          [],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i7.RandomExerciseResponse>>.value(
                _i6.dummyValue<_i5.ApiResult<_i7.RandomExerciseResponse>>(
          this,
          Invocation.method(
            #getRandomExercises,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i7.RandomExerciseResponse>>);

  @override
  _i4.Future<_i5.ApiResult<_i8.FoodCategoriesResponse>> getMealsCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsCategories,
          [],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i8.FoodCategoriesResponse>>.value(
                _i6.dummyValue<_i5.ApiResult<_i8.FoodCategoriesResponse>>(
          this,
          Invocation.method(
            #getMealsCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i8.FoodCategoriesResponse>>);

  @override
  _i4.Future<_i5.ApiResult<_i9.ExercisesResponse>> getAllExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExercises,
          [],
        ),
        returnValue: _i4.Future<_i5.ApiResult<_i9.ExercisesResponse>>.value(
            _i6.dummyValue<_i5.ApiResult<_i9.ExercisesResponse>>(
          this,
          Invocation.method(
            #getAllExercises,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i9.ExercisesResponse>>);
}

/// A class which mocks [GetAllMusclesGroupsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllMusclesGroupsUseCase extends _i1.Mock
    implements _i10.GetAllMusclesGroupsUseCase {
  MockGetAllMusclesGroupsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i11.GetAllMusclesGroupsReponse>> invoke() =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i11.GetAllMusclesGroupsReponse>>.value(
                _i6.dummyValue<_i5.ApiResult<_i11.GetAllMusclesGroupsReponse>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i11.GetAllMusclesGroupsReponse>>);
}

/// A class which mocks [GetAllMusclesByMuscleGroupIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllMusclesByMuscleGroupIdUseCase extends _i1.Mock
    implements _i12.GetAllMusclesByMuscleGroupIdUseCase {
  MockGetAllMusclesByMuscleGroupIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i13.GetAllMusclesByMuscleGroupIdReponse>> invoke(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [id],
        ),
        returnValue: _i4.Future<
                _i5.ApiResult<_i13.GetAllMusclesByMuscleGroupIdReponse>>.value(
            _i6.dummyValue<
                _i5.ApiResult<_i13.GetAllMusclesByMuscleGroupIdReponse>>(
          this,
          Invocation.method(
            #invoke,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i13.GetAllMusclesByMuscleGroupIdReponse>>);
}

/// A class which mocks [GetProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataUseCase extends _i1.Mock
    implements _i14.GetProfileDataUseCase {
  MockGetProfileDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProfileRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProfileRepository);

  @override
  _i4.Future<_i5.ApiResult<_i15.UserResponse>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i5.ApiResult<_i15.UserResponse>>.value(
            _i6.dummyValue<_i5.ApiResult<_i15.UserResponse>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i15.UserResponse>>);
}
